/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as AuthenticatedIndexRouteImport } from './routes/_authenticated/index'
import { Route as AuthenticatedResultsRouteImport } from './routes/_authenticated/results'
import { Route as AuthenticatedProfileRouteImport } from './routes/_authenticated/profile'
import { Route as AuthenticatedExploreRouteImport } from './routes/_authenticated/explore'
import { Route as AuthenticatedExamsRouteImport } from './routes/_authenticated/exams'
import { Route as AuthenticatedCreateRouteImport } from './routes/_authenticated/create'
import { Route as AuthenticatedAdminRouteRouteImport } from './routes/_authenticated/admin/route'
import { Route as AuthenticatedAdminIndexRouteImport } from './routes/_authenticated/admin/index'
import { Route as ShareQuizQuizIdRouteImport } from './routes/share.quiz.$quizId'
import { Route as AuthenticatedQuizQuizIdRouteImport } from './routes/_authenticated/quiz.$quizId'
import { Route as AuthenticatedAdminStudentsRouteImport } from './routes/_authenticated/admin/students'
import { Route as AuthenticatedAdminSettingsRouteImport } from './routes/_authenticated/admin/settings'
import { Route as AuthenticatedAdminQuizzesRouteImport } from './routes/_authenticated/admin/quizzes'
import { Route as AuthenticatedAdminCreatorsRouteImport } from './routes/_authenticated/admin/creators'
import { Route as AuthenticatedQuizQuizIdIndexRouteImport } from './routes/_authenticated/quiz.$quizId.index'
import { Route as AuthenticatedAdminQuizzesIndexRouteImport } from './routes/_authenticated/admin/quizzes.index'
import { Route as AuthenticatedQuizQuizIdTakeRouteImport } from './routes/_authenticated/quiz.$quizId.take'
import { Route as AuthenticatedAdminQuizzesNewRouteImport } from './routes/_authenticated/admin/quizzes.new'
import { Route as AuthenticatedQuizQuizIdResultAttemptIdRouteImport } from './routes/_authenticated/quiz.$quizId.result.$attemptId'
import { Route as AuthenticatedAdminQuizzesIdResultsRouteImport } from './routes/_authenticated/admin/quizzes.$id.results'
import { Route as AuthenticatedAdminQuizzesIdEditRouteImport } from './routes/_authenticated/admin/quizzes.$id.edit'

const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedIndexRoute = AuthenticatedIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedResultsRoute = AuthenticatedResultsRouteImport.update({
  id: '/results',
  path: '/results',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedProfileRoute = AuthenticatedProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedExploreRoute = AuthenticatedExploreRouteImport.update({
  id: '/explore',
  path: '/explore',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedExamsRoute = AuthenticatedExamsRouteImport.update({
  id: '/exams',
  path: '/exams',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedCreateRoute = AuthenticatedCreateRouteImport.update({
  id: '/create',
  path: '/create',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedAdminRouteRoute = AuthenticatedAdminRouteRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedAdminIndexRoute = AuthenticatedAdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthenticatedAdminRouteRoute,
} as any)
const ShareQuizQuizIdRoute = ShareQuizQuizIdRouteImport.update({
  id: '/share/quiz/$quizId',
  path: '/share/quiz/$quizId',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedQuizQuizIdRoute = AuthenticatedQuizQuizIdRouteImport.update({
  id: '/quiz/$quizId',
  path: '/quiz/$quizId',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedAdminStudentsRoute =
  AuthenticatedAdminStudentsRouteImport.update({
    id: '/students',
    path: '/students',
    getParentRoute: () => AuthenticatedAdminRouteRoute,
  } as any)
const AuthenticatedAdminSettingsRoute =
  AuthenticatedAdminSettingsRouteImport.update({
    id: '/settings',
    path: '/settings',
    getParentRoute: () => AuthenticatedAdminRouteRoute,
  } as any)
const AuthenticatedAdminQuizzesRoute =
  AuthenticatedAdminQuizzesRouteImport.update({
    id: '/quizzes',
    path: '/quizzes',
    getParentRoute: () => AuthenticatedAdminRouteRoute,
  } as any)
const AuthenticatedAdminCreatorsRoute =
  AuthenticatedAdminCreatorsRouteImport.update({
    id: '/creators',
    path: '/creators',
    getParentRoute: () => AuthenticatedAdminRouteRoute,
  } as any)
const AuthenticatedQuizQuizIdIndexRoute =
  AuthenticatedQuizQuizIdIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AuthenticatedQuizQuizIdRoute,
  } as any)
const AuthenticatedAdminQuizzesIndexRoute =
  AuthenticatedAdminQuizzesIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AuthenticatedAdminQuizzesRoute,
  } as any)
const AuthenticatedQuizQuizIdTakeRoute =
  AuthenticatedQuizQuizIdTakeRouteImport.update({
    id: '/take',
    path: '/take',
    getParentRoute: () => AuthenticatedQuizQuizIdRoute,
  } as any)
const AuthenticatedAdminQuizzesNewRoute =
  AuthenticatedAdminQuizzesNewRouteImport.update({
    id: '/new',
    path: '/new',
    getParentRoute: () => AuthenticatedAdminQuizzesRoute,
  } as any)
const AuthenticatedQuizQuizIdResultAttemptIdRoute =
  AuthenticatedQuizQuizIdResultAttemptIdRouteImport.update({
    id: '/result/$attemptId',
    path: '/result/$attemptId',
    getParentRoute: () => AuthenticatedQuizQuizIdRoute,
  } as any)
const AuthenticatedAdminQuizzesIdResultsRoute =
  AuthenticatedAdminQuizzesIdResultsRouteImport.update({
    id: '/$id/results',
    path: '/$id/results',
    getParentRoute: () => AuthenticatedAdminQuizzesRoute,
  } as any)
const AuthenticatedAdminQuizzesIdEditRoute =
  AuthenticatedAdminQuizzesIdEditRouteImport.update({
    id: '/$id/edit',
    path: '/$id/edit',
    getParentRoute: () => AuthenticatedAdminQuizzesRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof AuthenticatedIndexRoute
  '/auth': typeof AuthRoute
  '/admin': typeof AuthenticatedAdminRouteRouteWithChildren
  '/create': typeof AuthenticatedCreateRoute
  '/exams': typeof AuthenticatedExamsRoute
  '/explore': typeof AuthenticatedExploreRoute
  '/profile': typeof AuthenticatedProfileRoute
  '/results': typeof AuthenticatedResultsRoute
  '/admin/creators': typeof AuthenticatedAdminCreatorsRoute
  '/admin/quizzes': typeof AuthenticatedAdminQuizzesRouteWithChildren
  '/admin/settings': typeof AuthenticatedAdminSettingsRoute
  '/admin/students': typeof AuthenticatedAdminStudentsRoute
  '/quiz/$quizId': typeof AuthenticatedQuizQuizIdRouteWithChildren
  '/share/quiz/$quizId': typeof ShareQuizQuizIdRoute
  '/admin/': typeof AuthenticatedAdminIndexRoute
  '/admin/quizzes/new': typeof AuthenticatedAdminQuizzesNewRoute
  '/quiz/$quizId/take': typeof AuthenticatedQuizQuizIdTakeRoute
  '/admin/quizzes/': typeof AuthenticatedAdminQuizzesIndexRoute
  '/quiz/$quizId/': typeof AuthenticatedQuizQuizIdIndexRoute
  '/admin/quizzes/$id/edit': typeof AuthenticatedAdminQuizzesIdEditRoute
  '/admin/quizzes/$id/results': typeof AuthenticatedAdminQuizzesIdResultsRoute
  '/quiz/$quizId/result/$attemptId': typeof AuthenticatedQuizQuizIdResultAttemptIdRoute
}
export interface FileRoutesByTo {
  '/auth': typeof AuthRoute
  '/create': typeof AuthenticatedCreateRoute
  '/exams': typeof AuthenticatedExamsRoute
  '/explore': typeof AuthenticatedExploreRoute
  '/profile': typeof AuthenticatedProfileRoute
  '/results': typeof AuthenticatedResultsRoute
  '/': typeof AuthenticatedIndexRoute
  '/admin/creators': typeof AuthenticatedAdminCreatorsRoute
  '/admin/settings': typeof AuthenticatedAdminSettingsRoute
  '/admin/students': typeof AuthenticatedAdminStudentsRoute
  '/share/quiz/$quizId': typeof ShareQuizQuizIdRoute
  '/admin': typeof AuthenticatedAdminIndexRoute
  '/admin/quizzes/new': typeof AuthenticatedAdminQuizzesNewRoute
  '/quiz/$quizId/take': typeof AuthenticatedQuizQuizIdTakeRoute
  '/admin/quizzes': typeof AuthenticatedAdminQuizzesIndexRoute
  '/quiz/$quizId': typeof AuthenticatedQuizQuizIdIndexRoute
  '/admin/quizzes/$id/edit': typeof AuthenticatedAdminQuizzesIdEditRoute
  '/admin/quizzes/$id/results': typeof AuthenticatedAdminQuizzesIdResultsRoute
  '/quiz/$quizId/result/$attemptId': typeof AuthenticatedQuizQuizIdResultAttemptIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/auth': typeof AuthRoute
  '/_authenticated/admin': typeof AuthenticatedAdminRouteRouteWithChildren
  '/_authenticated/create': typeof AuthenticatedCreateRoute
  '/_authenticated/exams': typeof AuthenticatedExamsRoute
  '/_authenticated/explore': typeof AuthenticatedExploreRoute
  '/_authenticated/profile': typeof AuthenticatedProfileRoute
  '/_authenticated/results': typeof AuthenticatedResultsRoute
  '/_authenticated/': typeof AuthenticatedIndexRoute
  '/_authenticated/admin/creators': typeof AuthenticatedAdminCreatorsRoute
  '/_authenticated/admin/quizzes': typeof AuthenticatedAdminQuizzesRouteWithChildren
  '/_authenticated/admin/settings': typeof AuthenticatedAdminSettingsRoute
  '/_authenticated/admin/students': typeof AuthenticatedAdminStudentsRoute
  '/_authenticated/quiz/$quizId': typeof AuthenticatedQuizQuizIdRouteWithChildren
  '/share/quiz/$quizId': typeof ShareQuizQuizIdRoute
  '/_authenticated/admin/': typeof AuthenticatedAdminIndexRoute
  '/_authenticated/admin/quizzes/new': typeof AuthenticatedAdminQuizzesNewRoute
  '/_authenticated/quiz/$quizId/take': typeof AuthenticatedQuizQuizIdTakeRoute
  '/_authenticated/admin/quizzes/': typeof AuthenticatedAdminQuizzesIndexRoute
  '/_authenticated/quiz/$quizId/': typeof AuthenticatedQuizQuizIdIndexRoute
  '/_authenticated/admin/quizzes/$id/edit': typeof AuthenticatedAdminQuizzesIdEditRoute
  '/_authenticated/admin/quizzes/$id/results': typeof AuthenticatedAdminQuizzesIdResultsRoute
  '/_authenticated/quiz/$quizId/result/$attemptId': typeof AuthenticatedQuizQuizIdResultAttemptIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/admin'
    | '/create'
    | '/exams'
    | '/explore'
    | '/profile'
    | '/results'
    | '/admin/creators'
    | '/admin/quizzes'
    | '/admin/settings'
    | '/admin/students'
    | '/quiz/$quizId'
    | '/share/quiz/$quizId'
    | '/admin/'
    | '/admin/quizzes/new'
    | '/quiz/$quizId/take'
    | '/admin/quizzes/'
    | '/quiz/$quizId/'
    | '/admin/quizzes/$id/edit'
    | '/admin/quizzes/$id/results'
    | '/quiz/$quizId/result/$attemptId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/auth'
    | '/create'
    | '/exams'
    | '/explore'
    | '/profile'
    | '/results'
    | '/'
    | '/admin/creators'
    | '/admin/settings'
    | '/admin/students'
    | '/share/quiz/$quizId'
    | '/admin'
    | '/admin/quizzes/new'
    | '/quiz/$quizId/take'
    | '/admin/quizzes'
    | '/quiz/$quizId'
    | '/admin/quizzes/$id/edit'
    | '/admin/quizzes/$id/results'
    | '/quiz/$quizId/result/$attemptId'
  id:
    | '__root__'
    | '/_authenticated'
    | '/auth'
    | '/_authenticated/admin'
    | '/_authenticated/create'
    | '/_authenticated/exams'
    | '/_authenticated/explore'
    | '/_authenticated/profile'
    | '/_authenticated/results'
    | '/_authenticated/'
    | '/_authenticated/admin/creators'
    | '/_authenticated/admin/quizzes'
    | '/_authenticated/admin/settings'
    | '/_authenticated/admin/students'
    | '/_authenticated/quiz/$quizId'
    | '/share/quiz/$quizId'
    | '/_authenticated/admin/'
    | '/_authenticated/admin/quizzes/new'
    | '/_authenticated/quiz/$quizId/take'
    | '/_authenticated/admin/quizzes/'
    | '/_authenticated/quiz/$quizId/'
    | '/_authenticated/admin/quizzes/$id/edit'
    | '/_authenticated/admin/quizzes/$id/results'
    | '/_authenticated/quiz/$quizId/result/$attemptId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AuthRoute: typeof AuthRoute
  ShareQuizQuizIdRoute: typeof ShareQuizQuizIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/': {
      id: '/_authenticated/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/results': {
      id: '/_authenticated/results'
      path: '/results'
      fullPath: '/results'
      preLoaderRoute: typeof AuthenticatedResultsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/profile': {
      id: '/_authenticated/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof AuthenticatedProfileRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/explore': {
      id: '/_authenticated/explore'
      path: '/explore'
      fullPath: '/explore'
      preLoaderRoute: typeof AuthenticatedExploreRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/exams': {
      id: '/_authenticated/exams'
      path: '/exams'
      fullPath: '/exams'
      preLoaderRoute: typeof AuthenticatedExamsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/create': {
      id: '/_authenticated/create'
      path: '/create'
      fullPath: '/create'
      preLoaderRoute: typeof AuthenticatedCreateRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/admin': {
      id: '/_authenticated/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AuthenticatedAdminRouteRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/admin/': {
      id: '/_authenticated/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AuthenticatedAdminIndexRouteImport
      parentRoute: typeof AuthenticatedAdminRouteRoute
    }
    '/share/quiz/$quizId': {
      id: '/share/quiz/$quizId'
      path: '/share/quiz/$quizId'
      fullPath: '/share/quiz/$quizId'
      preLoaderRoute: typeof ShareQuizQuizIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/quiz/$quizId': {
      id: '/_authenticated/quiz/$quizId'
      path: '/quiz/$quizId'
      fullPath: '/quiz/$quizId'
      preLoaderRoute: typeof AuthenticatedQuizQuizIdRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/admin/students': {
      id: '/_authenticated/admin/students'
      path: '/students'
      fullPath: '/admin/students'
      preLoaderRoute: typeof AuthenticatedAdminStudentsRouteImport
      parentRoute: typeof AuthenticatedAdminRouteRoute
    }
    '/_authenticated/admin/settings': {
      id: '/_authenticated/admin/settings'
      path: '/settings'
      fullPath: '/admin/settings'
      preLoaderRoute: typeof AuthenticatedAdminSettingsRouteImport
      parentRoute: typeof AuthenticatedAdminRouteRoute
    }
    '/_authenticated/admin/quizzes': {
      id: '/_authenticated/admin/quizzes'
      path: '/quizzes'
      fullPath: '/admin/quizzes'
      preLoaderRoute: typeof AuthenticatedAdminQuizzesRouteImport
      parentRoute: typeof AuthenticatedAdminRouteRoute
    }
    '/_authenticated/admin/creators': {
      id: '/_authenticated/admin/creators'
      path: '/creators'
      fullPath: '/admin/creators'
      preLoaderRoute: typeof AuthenticatedAdminCreatorsRouteImport
      parentRoute: typeof AuthenticatedAdminRouteRoute
    }
    '/_authenticated/quiz/$quizId/': {
      id: '/_authenticated/quiz/$quizId/'
      path: '/'
      fullPath: '/quiz/$quizId/'
      preLoaderRoute: typeof AuthenticatedQuizQuizIdIndexRouteImport
      parentRoute: typeof AuthenticatedQuizQuizIdRoute
    }
    '/_authenticated/admin/quizzes/': {
      id: '/_authenticated/admin/quizzes/'
      path: '/'
      fullPath: '/admin/quizzes/'
      preLoaderRoute: typeof AuthenticatedAdminQuizzesIndexRouteImport
      parentRoute: typeof AuthenticatedAdminQuizzesRoute
    }
    '/_authenticated/quiz/$quizId/take': {
      id: '/_authenticated/quiz/$quizId/take'
      path: '/take'
      fullPath: '/quiz/$quizId/take'
      preLoaderRoute: typeof AuthenticatedQuizQuizIdTakeRouteImport
      parentRoute: typeof AuthenticatedQuizQuizIdRoute
    }
    '/_authenticated/admin/quizzes/new': {
      id: '/_authenticated/admin/quizzes/new'
      path: '/new'
      fullPath: '/admin/quizzes/new'
      preLoaderRoute: typeof AuthenticatedAdminQuizzesNewRouteImport
      parentRoute: typeof AuthenticatedAdminQuizzesRoute
    }
    '/_authenticated/quiz/$quizId/result/$attemptId': {
      id: '/_authenticated/quiz/$quizId/result/$attemptId'
      path: '/result/$attemptId'
      fullPath: '/quiz/$quizId/result/$attemptId'
      preLoaderRoute: typeof AuthenticatedQuizQuizIdResultAttemptIdRouteImport
      parentRoute: typeof AuthenticatedQuizQuizIdRoute
    }
    '/_authenticated/admin/quizzes/$id/results': {
      id: '/_authenticated/admin/quizzes/$id/results'
      path: '/$id/results'
      fullPath: '/admin/quizzes/$id/results'
      preLoaderRoute: typeof AuthenticatedAdminQuizzesIdResultsRouteImport
      parentRoute: typeof AuthenticatedAdminQuizzesRoute
    }
    '/_authenticated/admin/quizzes/$id/edit': {
      id: '/_authenticated/admin/quizzes/$id/edit'
      path: '/$id/edit'
      fullPath: '/admin/quizzes/$id/edit'
      preLoaderRoute: typeof AuthenticatedAdminQuizzesIdEditRouteImport
      parentRoute: typeof AuthenticatedAdminQuizzesRoute
    }
  }
}

interface AuthenticatedAdminQuizzesRouteChildren {
  AuthenticatedAdminQuizzesNewRoute: typeof AuthenticatedAdminQuizzesNewRoute
  AuthenticatedAdminQuizzesIndexRoute: typeof AuthenticatedAdminQuizzesIndexRoute
  AuthenticatedAdminQuizzesIdEditRoute: typeof AuthenticatedAdminQuizzesIdEditRoute
  AuthenticatedAdminQuizzesIdResultsRoute: typeof AuthenticatedAdminQuizzesIdResultsRoute
}

const AuthenticatedAdminQuizzesRouteChildren: AuthenticatedAdminQuizzesRouteChildren =
  {
    AuthenticatedAdminQuizzesNewRoute: AuthenticatedAdminQuizzesNewRoute,
    AuthenticatedAdminQuizzesIndexRoute: AuthenticatedAdminQuizzesIndexRoute,
    AuthenticatedAdminQuizzesIdEditRoute: AuthenticatedAdminQuizzesIdEditRoute,
    AuthenticatedAdminQuizzesIdResultsRoute:
      AuthenticatedAdminQuizzesIdResultsRoute,
  }

const AuthenticatedAdminQuizzesRouteWithChildren =
  AuthenticatedAdminQuizzesRoute._addFileChildren(
    AuthenticatedAdminQuizzesRouteChildren,
  )

interface AuthenticatedAdminRouteRouteChildren {
  AuthenticatedAdminCreatorsRoute: typeof AuthenticatedAdminCreatorsRoute
  AuthenticatedAdminQuizzesRoute: typeof AuthenticatedAdminQuizzesRouteWithChildren
  AuthenticatedAdminSettingsRoute: typeof AuthenticatedAdminSettingsRoute
  AuthenticatedAdminStudentsRoute: typeof AuthenticatedAdminStudentsRoute
  AuthenticatedAdminIndexRoute: typeof AuthenticatedAdminIndexRoute
}

const AuthenticatedAdminRouteRouteChildren: AuthenticatedAdminRouteRouteChildren =
  {
    AuthenticatedAdminCreatorsRoute: AuthenticatedAdminCreatorsRoute,
    AuthenticatedAdminQuizzesRoute: AuthenticatedAdminQuizzesRouteWithChildren,
    AuthenticatedAdminSettingsRoute: AuthenticatedAdminSettingsRoute,
    AuthenticatedAdminStudentsRoute: AuthenticatedAdminStudentsRoute,
    AuthenticatedAdminIndexRoute: AuthenticatedAdminIndexRoute,
  }

const AuthenticatedAdminRouteRouteWithChildren =
  AuthenticatedAdminRouteRoute._addFileChildren(
    AuthenticatedAdminRouteRouteChildren,
  )

interface AuthenticatedQuizQuizIdRouteChildren {
  AuthenticatedQuizQuizIdTakeRoute: typeof AuthenticatedQuizQuizIdTakeRoute
  AuthenticatedQuizQuizIdIndexRoute: typeof AuthenticatedQuizQuizIdIndexRoute
  AuthenticatedQuizQuizIdResultAttemptIdRoute: typeof AuthenticatedQuizQuizIdResultAttemptIdRoute
}

const AuthenticatedQuizQuizIdRouteChildren: AuthenticatedQuizQuizIdRouteChildren =
  {
    AuthenticatedQuizQuizIdTakeRoute: AuthenticatedQuizQuizIdTakeRoute,
    AuthenticatedQuizQuizIdIndexRoute: AuthenticatedQuizQuizIdIndexRoute,
    AuthenticatedQuizQuizIdResultAttemptIdRoute:
      AuthenticatedQuizQuizIdResultAttemptIdRoute,
  }

const AuthenticatedQuizQuizIdRouteWithChildren =
  AuthenticatedQuizQuizIdRoute._addFileChildren(
    AuthenticatedQuizQuizIdRouteChildren,
  )

interface AuthenticatedRouteRouteChildren {
  AuthenticatedAdminRouteRoute: typeof AuthenticatedAdminRouteRouteWithChildren
  AuthenticatedCreateRoute: typeof AuthenticatedCreateRoute
  AuthenticatedExamsRoute: typeof AuthenticatedExamsRoute
  AuthenticatedExploreRoute: typeof AuthenticatedExploreRoute
  AuthenticatedProfileRoute: typeof AuthenticatedProfileRoute
  AuthenticatedResultsRoute: typeof AuthenticatedResultsRoute
  AuthenticatedIndexRoute: typeof AuthenticatedIndexRoute
  AuthenticatedQuizQuizIdRoute: typeof AuthenticatedQuizQuizIdRouteWithChildren
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedAdminRouteRoute: AuthenticatedAdminRouteRouteWithChildren,
  AuthenticatedCreateRoute: AuthenticatedCreateRoute,
  AuthenticatedExamsRoute: AuthenticatedExamsRoute,
  AuthenticatedExploreRoute: AuthenticatedExploreRoute,
  AuthenticatedProfileRoute: AuthenticatedProfileRoute,
  AuthenticatedResultsRoute: AuthenticatedResultsRoute,
  AuthenticatedIndexRoute: AuthenticatedIndexRoute,
  AuthenticatedQuizQuizIdRoute: AuthenticatedQuizQuizIdRouteWithChildren,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AuthRoute: AuthRoute,
  ShareQuizQuizIdRoute: ShareQuizQuizIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
