/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as AuthenticatedIndexRouteImport } from './routes/_authenticated/index'
import { Route as AuthenticatedWalletRouteImport } from './routes/_authenticated/wallet'
import { Route as AuthenticatedSupportRouteImport } from './routes/_authenticated/support'
import { Route as AuthenticatedResultsRouteImport } from './routes/_authenticated/results'
import { Route as AuthenticatedNotificationsRouteImport } from './routes/_authenticated/notifications'
import { Route as AuthenticatedExploreRouteImport } from './routes/_authenticated/explore'
import { Route as AuthenticatedExamsRouteImport } from './routes/_authenticated/exams'
import { Route as AuthenticatedCreateRouteImport } from './routes/_authenticated/create'
import { Route as AuthenticatedAdsRouteImport } from './routes/_authenticated/ads'
import { Route as AuthenticatedAdminRouteRouteImport } from './routes/_authenticated/admin/route'
import { Route as AuthenticatedProfileIndexRouteImport } from './routes/_authenticated/profile.index'
import { Route as AuthenticatedMessagesIndexRouteImport } from './routes/_authenticated/messages.index'
import { Route as AuthenticatedAdminIndexRouteImport } from './routes/_authenticated/admin/index'
import { Route as ShareQuizQuizIdRouteImport } from './routes/share.quiz.$quizId'
import { Route as AuthenticatedQuizQuizIdRouteImport } from './routes/_authenticated/quiz.$quizId'
import { Route as AuthenticatedProfileUserIdRouteImport } from './routes/_authenticated/profile.$userId'
import { Route as AuthenticatedMessagesUserIdRouteImport } from './routes/_authenticated/messages.$userId'
import { Route as AuthenticatedExamExamIdRouteImport } from './routes/_authenticated/exam.$examId'
import { Route as AuthenticatedAdminUsersRouteImport } from './routes/_authenticated/admin/users'
import { Route as AuthenticatedAdminStudentsRouteImport } from './routes/_authenticated/admin/students'
import { Route as AuthenticatedAdminSettingsRouteImport } from './routes/_authenticated/admin/settings'
import { Route as AuthenticatedAdminQuizzesRouteImport } from './routes/_authenticated/admin/quizzes'
import { Route as AuthenticatedAdminProofsRouteImport } from './routes/_authenticated/admin/proofs'
import { Route as AuthenticatedAdminPaymentsRouteImport } from './routes/_authenticated/admin/payments'
import { Route as AuthenticatedAdminNotificationsRouteImport } from './routes/_authenticated/admin/notifications'
import { Route as AuthenticatedAdminGuidesRouteImport } from './routes/_authenticated/admin/guides'
import { Route as AuthenticatedAdminExamsRouteImport } from './routes/_authenticated/admin/exams'
import { Route as AuthenticatedAdminCreatorsRouteImport } from './routes/_authenticated/admin/creators'
import { Route as AuthenticatedAdminAdsRouteImport } from './routes/_authenticated/admin/ads'
import { Route as AuthenticatedQuizQuizIdIndexRouteImport } from './routes/_authenticated/quiz.$quizId.index'
import { Route as AuthenticatedAdminQuizzesIndexRouteImport } from './routes/_authenticated/admin/quizzes.index'
import { Route as AuthenticatedAdminExamsIndexRouteImport } from './routes/_authenticated/admin/exams.index'
import { Route as ApiPublicHooksMonnifyRouteImport } from './routes/api/public/hooks/monnify'
import { Route as AuthenticatedQuizQuizIdTakeRouteImport } from './routes/_authenticated/quiz.$quizId.take'
import { Route as AuthenticatedMessagesGroupGroupIdRouteImport } from './routes/_authenticated/messages.group.$groupId'
import { Route as AuthenticatedAdminQuizzesNewRouteImport } from './routes/_authenticated/admin/quizzes.new'
import { Route as AuthenticatedQuizQuizIdResultAttemptIdRouteImport } from './routes/_authenticated/quiz.$quizId.result.$attemptId'
import { Route as AuthenticatedAdminQuizzesIdResultsRouteImport } from './routes/_authenticated/admin/quizzes.$id.results'
import { Route as AuthenticatedAdminQuizzesIdEditRouteImport } from './routes/_authenticated/admin/quizzes.$id.edit'
import { Route as AuthenticatedAdminExamsIdEditRouteImport } from './routes/_authenticated/admin/exams.$id.edit'

const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedIndexRoute = AuthenticatedIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedWalletRoute = AuthenticatedWalletRouteImport.update({
  id: '/wallet',
  path: '/wallet',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedSupportRoute = AuthenticatedSupportRouteImport.update({
  id: '/support',
  path: '/support',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedResultsRoute = AuthenticatedResultsRouteImport.update({
  id: '/results',
  path: '/results',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedNotificationsRoute =
  AuthenticatedNotificationsRouteImport.update({
    id: '/notifications',
    path: '/notifications',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedExploreRoute = AuthenticatedExploreRouteImport.update({
  id: '/explore',
  path: '/explore',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedExamsRoute = AuthenticatedExamsRouteImport.update({
  id: '/exams',
  path: '/exams',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedCreateRoute = AuthenticatedCreateRouteImport.update({
  id: '/create',
  path: '/create',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedAdsRoute = AuthenticatedAdsRouteImport.update({
  id: '/ads',
  path: '/ads',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedAdminRouteRoute = AuthenticatedAdminRouteRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedProfileIndexRoute =
  AuthenticatedProfileIndexRouteImport.update({
    id: '/profile/',
    path: '/profile/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedMessagesIndexRoute =
  AuthenticatedMessagesIndexRouteImport.update({
    id: '/messages/',
    path: '/messages/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedAdminIndexRoute = AuthenticatedAdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthenticatedAdminRouteRoute,
} as any)
const ShareQuizQuizIdRoute = ShareQuizQuizIdRouteImport.update({
  id: '/share/quiz/$quizId',
  path: '/share/quiz/$quizId',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedQuizQuizIdRoute = AuthenticatedQuizQuizIdRouteImport.update({
  id: '/quiz/$quizId',
  path: '/quiz/$quizId',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedProfileUserIdRoute =
  AuthenticatedProfileUserIdRouteImport.update({
    id: '/profile/$userId',
    path: '/profile/$userId',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedMessagesUserIdRoute =
  AuthenticatedMessagesUserIdRouteImport.update({
    id: '/messages/$userId',
    path: '/messages/$userId',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedExamExamIdRoute = AuthenticatedExamExamIdRouteImport.update({
  id: '/exam/$examId',
  path: '/exam/$examId',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedAdminUsersRoute = AuthenticatedAdminUsersRouteImport.update({
  id: '/users',
  path: '/users',
  getParentRoute: () => AuthenticatedAdminRouteRoute,
} as any)
const AuthenticatedAdminStudentsRoute =
  AuthenticatedAdminStudentsRouteImport.update({
    id: '/students',
    path: '/students',
    getParentRoute: () => AuthenticatedAdminRouteRoute,
  } as any)
const AuthenticatedAdminSettingsRoute =
  AuthenticatedAdminSettingsRouteImport.update({
    id: '/settings',
    path: '/settings',
    getParentRoute: () => AuthenticatedAdminRouteRoute,
  } as any)
const AuthenticatedAdminQuizzesRoute =
  AuthenticatedAdminQuizzesRouteImport.update({
    id: '/quizzes',
    path: '/quizzes',
    getParentRoute: () => AuthenticatedAdminRouteRoute,
  } as any)
const AuthenticatedAdminProofsRoute =
  AuthenticatedAdminProofsRouteImport.update({
    id: '/proofs',
    path: '/proofs',
    getParentRoute: () => AuthenticatedAdminRouteRoute,
  } as any)
const AuthenticatedAdminPaymentsRoute =
  AuthenticatedAdminPaymentsRouteImport.update({
    id: '/payments',
    path: '/payments',
    getParentRoute: () => AuthenticatedAdminRouteRoute,
  } as any)
const AuthenticatedAdminNotificationsRoute =
  AuthenticatedAdminNotificationsRouteImport.update({
    id: '/notifications',
    path: '/notifications',
    getParentRoute: () => AuthenticatedAdminRouteRoute,
  } as any)
const AuthenticatedAdminGuidesRoute =
  AuthenticatedAdminGuidesRouteImport.update({
    id: '/guides',
    path: '/guides',
    getParentRoute: () => AuthenticatedAdminRouteRoute,
  } as any)
const AuthenticatedAdminExamsRoute = AuthenticatedAdminExamsRouteImport.update({
  id: '/exams',
  path: '/exams',
  getParentRoute: () => AuthenticatedAdminRouteRoute,
} as any)
const AuthenticatedAdminCreatorsRoute =
  AuthenticatedAdminCreatorsRouteImport.update({
    id: '/creators',
    path: '/creators',
    getParentRoute: () => AuthenticatedAdminRouteRoute,
  } as any)
const AuthenticatedAdminAdsRoute = AuthenticatedAdminAdsRouteImport.update({
  id: '/ads',
  path: '/ads',
  getParentRoute: () => AuthenticatedAdminRouteRoute,
} as any)
const AuthenticatedQuizQuizIdIndexRoute =
  AuthenticatedQuizQuizIdIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AuthenticatedQuizQuizIdRoute,
  } as any)
const AuthenticatedAdminQuizzesIndexRoute =
  AuthenticatedAdminQuizzesIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AuthenticatedAdminQuizzesRoute,
  } as any)
const AuthenticatedAdminExamsIndexRoute =
  AuthenticatedAdminExamsIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AuthenticatedAdminExamsRoute,
  } as any)
const ApiPublicHooksMonnifyRoute = ApiPublicHooksMonnifyRouteImport.update({
  id: '/api/public/hooks/monnify',
  path: '/api/public/hooks/monnify',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedQuizQuizIdTakeRoute =
  AuthenticatedQuizQuizIdTakeRouteImport.update({
    id: '/take',
    path: '/take',
    getParentRoute: () => AuthenticatedQuizQuizIdRoute,
  } as any)
const AuthenticatedMessagesGroupGroupIdRoute =
  AuthenticatedMessagesGroupGroupIdRouteImport.update({
    id: '/messages/group/$groupId',
    path: '/messages/group/$groupId',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedAdminQuizzesNewRoute =
  AuthenticatedAdminQuizzesNewRouteImport.update({
    id: '/new',
    path: '/new',
    getParentRoute: () => AuthenticatedAdminQuizzesRoute,
  } as any)
const AuthenticatedQuizQuizIdResultAttemptIdRoute =
  AuthenticatedQuizQuizIdResultAttemptIdRouteImport.update({
    id: '/result/$attemptId',
    path: '/result/$attemptId',
    getParentRoute: () => AuthenticatedQuizQuizIdRoute,
  } as any)
const AuthenticatedAdminQuizzesIdResultsRoute =
  AuthenticatedAdminQuizzesIdResultsRouteImport.update({
    id: '/$id/results',
    path: '/$id/results',
    getParentRoute: () => AuthenticatedAdminQuizzesRoute,
  } as any)
const AuthenticatedAdminQuizzesIdEditRoute =
  AuthenticatedAdminQuizzesIdEditRouteImport.update({
    id: '/$id/edit',
    path: '/$id/edit',
    getParentRoute: () => AuthenticatedAdminQuizzesRoute,
  } as any)
const AuthenticatedAdminExamsIdEditRoute =
  AuthenticatedAdminExamsIdEditRouteImport.update({
    id: '/$id/edit',
    path: '/$id/edit',
    getParentRoute: () => AuthenticatedAdminExamsRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof AuthenticatedIndexRoute
  '/auth': typeof AuthRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/admin': typeof AuthenticatedAdminRouteRouteWithChildren
  '/ads': typeof AuthenticatedAdsRoute
  '/create': typeof AuthenticatedCreateRoute
  '/exams': typeof AuthenticatedExamsRoute
  '/explore': typeof AuthenticatedExploreRoute
  '/notifications': typeof AuthenticatedNotificationsRoute
  '/results': typeof AuthenticatedResultsRoute
  '/support': typeof AuthenticatedSupportRoute
  '/wallet': typeof AuthenticatedWalletRoute
  '/admin/ads': typeof AuthenticatedAdminAdsRoute
  '/admin/creators': typeof AuthenticatedAdminCreatorsRoute
  '/admin/exams': typeof AuthenticatedAdminExamsRouteWithChildren
  '/admin/guides': typeof AuthenticatedAdminGuidesRoute
  '/admin/notifications': typeof AuthenticatedAdminNotificationsRoute
  '/admin/payments': typeof AuthenticatedAdminPaymentsRoute
  '/admin/proofs': typeof AuthenticatedAdminProofsRoute
  '/admin/quizzes': typeof AuthenticatedAdminQuizzesRouteWithChildren
  '/admin/settings': typeof AuthenticatedAdminSettingsRoute
  '/admin/students': typeof AuthenticatedAdminStudentsRoute
  '/admin/users': typeof AuthenticatedAdminUsersRoute
  '/exam/$examId': typeof AuthenticatedExamExamIdRoute
  '/messages/$userId': typeof AuthenticatedMessagesUserIdRoute
  '/profile/$userId': typeof AuthenticatedProfileUserIdRoute
  '/quiz/$quizId': typeof AuthenticatedQuizQuizIdRouteWithChildren
  '/share/quiz/$quizId': typeof ShareQuizQuizIdRoute
  '/admin/': typeof AuthenticatedAdminIndexRoute
  '/messages/': typeof AuthenticatedMessagesIndexRoute
  '/profile/': typeof AuthenticatedProfileIndexRoute
  '/admin/quizzes/new': typeof AuthenticatedAdminQuizzesNewRoute
  '/messages/group/$groupId': typeof AuthenticatedMessagesGroupGroupIdRoute
  '/quiz/$quizId/take': typeof AuthenticatedQuizQuizIdTakeRoute
  '/api/public/hooks/monnify': typeof ApiPublicHooksMonnifyRoute
  '/admin/exams/': typeof AuthenticatedAdminExamsIndexRoute
  '/admin/quizzes/': typeof AuthenticatedAdminQuizzesIndexRoute
  '/quiz/$quizId/': typeof AuthenticatedQuizQuizIdIndexRoute
  '/admin/exams/$id/edit': typeof AuthenticatedAdminExamsIdEditRoute
  '/admin/quizzes/$id/edit': typeof AuthenticatedAdminQuizzesIdEditRoute
  '/admin/quizzes/$id/results': typeof AuthenticatedAdminQuizzesIdResultsRoute
  '/quiz/$quizId/result/$attemptId': typeof AuthenticatedQuizQuizIdResultAttemptIdRoute
}
export interface FileRoutesByTo {
  '/auth': typeof AuthRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/ads': typeof AuthenticatedAdsRoute
  '/create': typeof AuthenticatedCreateRoute
  '/exams': typeof AuthenticatedExamsRoute
  '/explore': typeof AuthenticatedExploreRoute
  '/notifications': typeof AuthenticatedNotificationsRoute
  '/results': typeof AuthenticatedResultsRoute
  '/support': typeof AuthenticatedSupportRoute
  '/wallet': typeof AuthenticatedWalletRoute
  '/': typeof AuthenticatedIndexRoute
  '/admin/ads': typeof AuthenticatedAdminAdsRoute
  '/admin/creators': typeof AuthenticatedAdminCreatorsRoute
  '/admin/guides': typeof AuthenticatedAdminGuidesRoute
  '/admin/notifications': typeof AuthenticatedAdminNotificationsRoute
  '/admin/payments': typeof AuthenticatedAdminPaymentsRoute
  '/admin/proofs': typeof AuthenticatedAdminProofsRoute
  '/admin/settings': typeof AuthenticatedAdminSettingsRoute
  '/admin/students': typeof AuthenticatedAdminStudentsRoute
  '/admin/users': typeof AuthenticatedAdminUsersRoute
  '/exam/$examId': typeof AuthenticatedExamExamIdRoute
  '/messages/$userId': typeof AuthenticatedMessagesUserIdRoute
  '/profile/$userId': typeof AuthenticatedProfileUserIdRoute
  '/share/quiz/$quizId': typeof ShareQuizQuizIdRoute
  '/admin': typeof AuthenticatedAdminIndexRoute
  '/messages': typeof AuthenticatedMessagesIndexRoute
  '/profile': typeof AuthenticatedProfileIndexRoute
  '/admin/quizzes/new': typeof AuthenticatedAdminQuizzesNewRoute
  '/messages/group/$groupId': typeof AuthenticatedMessagesGroupGroupIdRoute
  '/quiz/$quizId/take': typeof AuthenticatedQuizQuizIdTakeRoute
  '/api/public/hooks/monnify': typeof ApiPublicHooksMonnifyRoute
  '/admin/exams': typeof AuthenticatedAdminExamsIndexRoute
  '/admin/quizzes': typeof AuthenticatedAdminQuizzesIndexRoute
  '/quiz/$quizId': typeof AuthenticatedQuizQuizIdIndexRoute
  '/admin/exams/$id/edit': typeof AuthenticatedAdminExamsIdEditRoute
  '/admin/quizzes/$id/edit': typeof AuthenticatedAdminQuizzesIdEditRoute
  '/admin/quizzes/$id/results': typeof AuthenticatedAdminQuizzesIdResultsRoute
  '/quiz/$quizId/result/$attemptId': typeof AuthenticatedQuizQuizIdResultAttemptIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/auth': typeof AuthRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/_authenticated/admin': typeof AuthenticatedAdminRouteRouteWithChildren
  '/_authenticated/ads': typeof AuthenticatedAdsRoute
  '/_authenticated/create': typeof AuthenticatedCreateRoute
  '/_authenticated/exams': typeof AuthenticatedExamsRoute
  '/_authenticated/explore': typeof AuthenticatedExploreRoute
  '/_authenticated/notifications': typeof AuthenticatedNotificationsRoute
  '/_authenticated/results': typeof AuthenticatedResultsRoute
  '/_authenticated/support': typeof AuthenticatedSupportRoute
  '/_authenticated/wallet': typeof AuthenticatedWalletRoute
  '/_authenticated/': typeof AuthenticatedIndexRoute
  '/_authenticated/admin/ads': typeof AuthenticatedAdminAdsRoute
  '/_authenticated/admin/creators': typeof AuthenticatedAdminCreatorsRoute
  '/_authenticated/admin/exams': typeof AuthenticatedAdminExamsRouteWithChildren
  '/_authenticated/admin/guides': typeof AuthenticatedAdminGuidesRoute
  '/_authenticated/admin/notifications': typeof AuthenticatedAdminNotificationsRoute
  '/_authenticated/admin/payments': typeof AuthenticatedAdminPaymentsRoute
  '/_authenticated/admin/proofs': typeof AuthenticatedAdminProofsRoute
  '/_authenticated/admin/quizzes': typeof AuthenticatedAdminQuizzesRouteWithChildren
  '/_authenticated/admin/settings': typeof AuthenticatedAdminSettingsRoute
  '/_authenticated/admin/students': typeof AuthenticatedAdminStudentsRoute
  '/_authenticated/admin/users': typeof AuthenticatedAdminUsersRoute
  '/_authenticated/exam/$examId': typeof AuthenticatedExamExamIdRoute
  '/_authenticated/messages/$userId': typeof AuthenticatedMessagesUserIdRoute
  '/_authenticated/profile/$userId': typeof AuthenticatedProfileUserIdRoute
  '/_authenticated/quiz/$quizId': typeof AuthenticatedQuizQuizIdRouteWithChildren
  '/share/quiz/$quizId': typeof ShareQuizQuizIdRoute
  '/_authenticated/admin/': typeof AuthenticatedAdminIndexRoute
  '/_authenticated/messages/': typeof AuthenticatedMessagesIndexRoute
  '/_authenticated/profile/': typeof AuthenticatedProfileIndexRoute
  '/_authenticated/admin/quizzes/new': typeof AuthenticatedAdminQuizzesNewRoute
  '/_authenticated/messages/group/$groupId': typeof AuthenticatedMessagesGroupGroupIdRoute
  '/_authenticated/quiz/$quizId/take': typeof AuthenticatedQuizQuizIdTakeRoute
  '/api/public/hooks/monnify': typeof ApiPublicHooksMonnifyRoute
  '/_authenticated/admin/exams/': typeof AuthenticatedAdminExamsIndexRoute
  '/_authenticated/admin/quizzes/': typeof AuthenticatedAdminQuizzesIndexRoute
  '/_authenticated/quiz/$quizId/': typeof AuthenticatedQuizQuizIdIndexRoute
  '/_authenticated/admin/exams/$id/edit': typeof AuthenticatedAdminExamsIdEditRoute
  '/_authenticated/admin/quizzes/$id/edit': typeof AuthenticatedAdminQuizzesIdEditRoute
  '/_authenticated/admin/quizzes/$id/results': typeof AuthenticatedAdminQuizzesIdResultsRoute
  '/_authenticated/quiz/$quizId/result/$attemptId': typeof AuthenticatedQuizQuizIdResultAttemptIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/sitemap.xml'
    | '/admin'
    | '/ads'
    | '/create'
    | '/exams'
    | '/explore'
    | '/notifications'
    | '/results'
    | '/support'
    | '/wallet'
    | '/admin/ads'
    | '/admin/creators'
    | '/admin/exams'
    | '/admin/guides'
    | '/admin/notifications'
    | '/admin/payments'
    | '/admin/proofs'
    | '/admin/quizzes'
    | '/admin/settings'
    | '/admin/students'
    | '/admin/users'
    | '/exam/$examId'
    | '/messages/$userId'
    | '/profile/$userId'
    | '/quiz/$quizId'
    | '/share/quiz/$quizId'
    | '/admin/'
    | '/messages/'
    | '/profile/'
    | '/admin/quizzes/new'
    | '/messages/group/$groupId'
    | '/quiz/$quizId/take'
    | '/api/public/hooks/monnify'
    | '/admin/exams/'
    | '/admin/quizzes/'
    | '/quiz/$quizId/'
    | '/admin/exams/$id/edit'
    | '/admin/quizzes/$id/edit'
    | '/admin/quizzes/$id/results'
    | '/quiz/$quizId/result/$attemptId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/auth'
    | '/sitemap.xml'
    | '/ads'
    | '/create'
    | '/exams'
    | '/explore'
    | '/notifications'
    | '/results'
    | '/support'
    | '/wallet'
    | '/'
    | '/admin/ads'
    | '/admin/creators'
    | '/admin/guides'
    | '/admin/notifications'
    | '/admin/payments'
    | '/admin/proofs'
    | '/admin/settings'
    | '/admin/students'
    | '/admin/users'
    | '/exam/$examId'
    | '/messages/$userId'
    | '/profile/$userId'
    | '/share/quiz/$quizId'
    | '/admin'
    | '/messages'
    | '/profile'
    | '/admin/quizzes/new'
    | '/messages/group/$groupId'
    | '/quiz/$quizId/take'
    | '/api/public/hooks/monnify'
    | '/admin/exams'
    | '/admin/quizzes'
    | '/quiz/$quizId'
    | '/admin/exams/$id/edit'
    | '/admin/quizzes/$id/edit'
    | '/admin/quizzes/$id/results'
    | '/quiz/$quizId/result/$attemptId'
  id:
    | '__root__'
    | '/_authenticated'
    | '/auth'
    | '/sitemap.xml'
    | '/_authenticated/admin'
    | '/_authenticated/ads'
    | '/_authenticated/create'
    | '/_authenticated/exams'
    | '/_authenticated/explore'
    | '/_authenticated/notifications'
    | '/_authenticated/results'
    | '/_authenticated/support'
    | '/_authenticated/wallet'
    | '/_authenticated/'
    | '/_authenticated/admin/ads'
    | '/_authenticated/admin/creators'
    | '/_authenticated/admin/exams'
    | '/_authenticated/admin/guides'
    | '/_authenticated/admin/notifications'
    | '/_authenticated/admin/payments'
    | '/_authenticated/admin/proofs'
    | '/_authenticated/admin/quizzes'
    | '/_authenticated/admin/settings'
    | '/_authenticated/admin/students'
    | '/_authenticated/admin/users'
    | '/_authenticated/exam/$examId'
    | '/_authenticated/messages/$userId'
    | '/_authenticated/profile/$userId'
    | '/_authenticated/quiz/$quizId'
    | '/share/quiz/$quizId'
    | '/_authenticated/admin/'
    | '/_authenticated/messages/'
    | '/_authenticated/profile/'
    | '/_authenticated/admin/quizzes/new'
    | '/_authenticated/messages/group/$groupId'
    | '/_authenticated/quiz/$quizId/take'
    | '/api/public/hooks/monnify'
    | '/_authenticated/admin/exams/'
    | '/_authenticated/admin/quizzes/'
    | '/_authenticated/quiz/$quizId/'
    | '/_authenticated/admin/exams/$id/edit'
    | '/_authenticated/admin/quizzes/$id/edit'
    | '/_authenticated/admin/quizzes/$id/results'
    | '/_authenticated/quiz/$quizId/result/$attemptId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AuthRoute: typeof AuthRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  ShareQuizQuizIdRoute: typeof ShareQuizQuizIdRoute
  ApiPublicHooksMonnifyRoute: typeof ApiPublicHooksMonnifyRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/': {
      id: '/_authenticated/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/wallet': {
      id: '/_authenticated/wallet'
      path: '/wallet'
      fullPath: '/wallet'
      preLoaderRoute: typeof AuthenticatedWalletRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/support': {
      id: '/_authenticated/support'
      path: '/support'
      fullPath: '/support'
      preLoaderRoute: typeof AuthenticatedSupportRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/results': {
      id: '/_authenticated/results'
      path: '/results'
      fullPath: '/results'
      preLoaderRoute: typeof AuthenticatedResultsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/notifications': {
      id: '/_authenticated/notifications'
      path: '/notifications'
      fullPath: '/notifications'
      preLoaderRoute: typeof AuthenticatedNotificationsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/explore': {
      id: '/_authenticated/explore'
      path: '/explore'
      fullPath: '/explore'
      preLoaderRoute: typeof AuthenticatedExploreRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/exams': {
      id: '/_authenticated/exams'
      path: '/exams'
      fullPath: '/exams'
      preLoaderRoute: typeof AuthenticatedExamsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/create': {
      id: '/_authenticated/create'
      path: '/create'
      fullPath: '/create'
      preLoaderRoute: typeof AuthenticatedCreateRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/ads': {
      id: '/_authenticated/ads'
      path: '/ads'
      fullPath: '/ads'
      preLoaderRoute: typeof AuthenticatedAdsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/admin': {
      id: '/_authenticated/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AuthenticatedAdminRouteRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/profile/': {
      id: '/_authenticated/profile/'
      path: '/profile'
      fullPath: '/profile/'
      preLoaderRoute: typeof AuthenticatedProfileIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/messages/': {
      id: '/_authenticated/messages/'
      path: '/messages'
      fullPath: '/messages/'
      preLoaderRoute: typeof AuthenticatedMessagesIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/admin/': {
      id: '/_authenticated/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AuthenticatedAdminIndexRouteImport
      parentRoute: typeof AuthenticatedAdminRouteRoute
    }
    '/share/quiz/$quizId': {
      id: '/share/quiz/$quizId'
      path: '/share/quiz/$quizId'
      fullPath: '/share/quiz/$quizId'
      preLoaderRoute: typeof ShareQuizQuizIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/quiz/$quizId': {
      id: '/_authenticated/quiz/$quizId'
      path: '/quiz/$quizId'
      fullPath: '/quiz/$quizId'
      preLoaderRoute: typeof AuthenticatedQuizQuizIdRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/profile/$userId': {
      id: '/_authenticated/profile/$userId'
      path: '/profile/$userId'
      fullPath: '/profile/$userId'
      preLoaderRoute: typeof AuthenticatedProfileUserIdRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/messages/$userId': {
      id: '/_authenticated/messages/$userId'
      path: '/messages/$userId'
      fullPath: '/messages/$userId'
      preLoaderRoute: typeof AuthenticatedMessagesUserIdRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/exam/$examId': {
      id: '/_authenticated/exam/$examId'
      path: '/exam/$examId'
      fullPath: '/exam/$examId'
      preLoaderRoute: typeof AuthenticatedExamExamIdRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/admin/users': {
      id: '/_authenticated/admin/users'
      path: '/users'
      fullPath: '/admin/users'
      preLoaderRoute: typeof AuthenticatedAdminUsersRouteImport
      parentRoute: typeof AuthenticatedAdminRouteRoute
    }
    '/_authenticated/admin/students': {
      id: '/_authenticated/admin/students'
      path: '/students'
      fullPath: '/admin/students'
      preLoaderRoute: typeof AuthenticatedAdminStudentsRouteImport
      parentRoute: typeof AuthenticatedAdminRouteRoute
    }
    '/_authenticated/admin/settings': {
      id: '/_authenticated/admin/settings'
      path: '/settings'
      fullPath: '/admin/settings'
      preLoaderRoute: typeof AuthenticatedAdminSettingsRouteImport
      parentRoute: typeof AuthenticatedAdminRouteRoute
    }
    '/_authenticated/admin/quizzes': {
      id: '/_authenticated/admin/quizzes'
      path: '/quizzes'
      fullPath: '/admin/quizzes'
      preLoaderRoute: typeof AuthenticatedAdminQuizzesRouteImport
      parentRoute: typeof AuthenticatedAdminRouteRoute
    }
    '/_authenticated/admin/proofs': {
      id: '/_authenticated/admin/proofs'
      path: '/proofs'
      fullPath: '/admin/proofs'
      preLoaderRoute: typeof AuthenticatedAdminProofsRouteImport
      parentRoute: typeof AuthenticatedAdminRouteRoute
    }
    '/_authenticated/admin/payments': {
      id: '/_authenticated/admin/payments'
      path: '/payments'
      fullPath: '/admin/payments'
      preLoaderRoute: typeof AuthenticatedAdminPaymentsRouteImport
      parentRoute: typeof AuthenticatedAdminRouteRoute
    }
    '/_authenticated/admin/notifications': {
      id: '/_authenticated/admin/notifications'
      path: '/notifications'
      fullPath: '/admin/notifications'
      preLoaderRoute: typeof AuthenticatedAdminNotificationsRouteImport
      parentRoute: typeof AuthenticatedAdminRouteRoute
    }
    '/_authenticated/admin/guides': {
      id: '/_authenticated/admin/guides'
      path: '/guides'
      fullPath: '/admin/guides'
      preLoaderRoute: typeof AuthenticatedAdminGuidesRouteImport
      parentRoute: typeof AuthenticatedAdminRouteRoute
    }
    '/_authenticated/admin/exams': {
      id: '/_authenticated/admin/exams'
      path: '/exams'
      fullPath: '/admin/exams'
      preLoaderRoute: typeof AuthenticatedAdminExamsRouteImport
      parentRoute: typeof AuthenticatedAdminRouteRoute
    }
    '/_authenticated/admin/creators': {
      id: '/_authenticated/admin/creators'
      path: '/creators'
      fullPath: '/admin/creators'
      preLoaderRoute: typeof AuthenticatedAdminCreatorsRouteImport
      parentRoute: typeof AuthenticatedAdminRouteRoute
    }
    '/_authenticated/admin/ads': {
      id: '/_authenticated/admin/ads'
      path: '/ads'
      fullPath: '/admin/ads'
      preLoaderRoute: typeof AuthenticatedAdminAdsRouteImport
      parentRoute: typeof AuthenticatedAdminRouteRoute
    }
    '/_authenticated/quiz/$quizId/': {
      id: '/_authenticated/quiz/$quizId/'
      path: '/'
      fullPath: '/quiz/$quizId/'
      preLoaderRoute: typeof AuthenticatedQuizQuizIdIndexRouteImport
      parentRoute: typeof AuthenticatedQuizQuizIdRoute
    }
    '/_authenticated/admin/quizzes/': {
      id: '/_authenticated/admin/quizzes/'
      path: '/'
      fullPath: '/admin/quizzes/'
      preLoaderRoute: typeof AuthenticatedAdminQuizzesIndexRouteImport
      parentRoute: typeof AuthenticatedAdminQuizzesRoute
    }
    '/_authenticated/admin/exams/': {
      id: '/_authenticated/admin/exams/'
      path: '/'
      fullPath: '/admin/exams/'
      preLoaderRoute: typeof AuthenticatedAdminExamsIndexRouteImport
      parentRoute: typeof AuthenticatedAdminExamsRoute
    }
    '/api/public/hooks/monnify': {
      id: '/api/public/hooks/monnify'
      path: '/api/public/hooks/monnify'
      fullPath: '/api/public/hooks/monnify'
      preLoaderRoute: typeof ApiPublicHooksMonnifyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/quiz/$quizId/take': {
      id: '/_authenticated/quiz/$quizId/take'
      path: '/take'
      fullPath: '/quiz/$quizId/take'
      preLoaderRoute: typeof AuthenticatedQuizQuizIdTakeRouteImport
      parentRoute: typeof AuthenticatedQuizQuizIdRoute
    }
    '/_authenticated/messages/group/$groupId': {
      id: '/_authenticated/messages/group/$groupId'
      path: '/messages/group/$groupId'
      fullPath: '/messages/group/$groupId'
      preLoaderRoute: typeof AuthenticatedMessagesGroupGroupIdRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/admin/quizzes/new': {
      id: '/_authenticated/admin/quizzes/new'
      path: '/new'
      fullPath: '/admin/quizzes/new'
      preLoaderRoute: typeof AuthenticatedAdminQuizzesNewRouteImport
      parentRoute: typeof AuthenticatedAdminQuizzesRoute
    }
    '/_authenticated/quiz/$quizId/result/$attemptId': {
      id: '/_authenticated/quiz/$quizId/result/$attemptId'
      path: '/result/$attemptId'
      fullPath: '/quiz/$quizId/result/$attemptId'
      preLoaderRoute: typeof AuthenticatedQuizQuizIdResultAttemptIdRouteImport
      parentRoute: typeof AuthenticatedQuizQuizIdRoute
    }
    '/_authenticated/admin/quizzes/$id/results': {
      id: '/_authenticated/admin/quizzes/$id/results'
      path: '/$id/results'
      fullPath: '/admin/quizzes/$id/results'
      preLoaderRoute: typeof AuthenticatedAdminQuizzesIdResultsRouteImport
      parentRoute: typeof AuthenticatedAdminQuizzesRoute
    }
    '/_authenticated/admin/quizzes/$id/edit': {
      id: '/_authenticated/admin/quizzes/$id/edit'
      path: '/$id/edit'
      fullPath: '/admin/quizzes/$id/edit'
      preLoaderRoute: typeof AuthenticatedAdminQuizzesIdEditRouteImport
      parentRoute: typeof AuthenticatedAdminQuizzesRoute
    }
    '/_authenticated/admin/exams/$id/edit': {
      id: '/_authenticated/admin/exams/$id/edit'
      path: '/$id/edit'
      fullPath: '/admin/exams/$id/edit'
      preLoaderRoute: typeof AuthenticatedAdminExamsIdEditRouteImport
      parentRoute: typeof AuthenticatedAdminExamsRoute
    }
  }
}

interface AuthenticatedAdminExamsRouteChildren {
  AuthenticatedAdminExamsIndexRoute: typeof AuthenticatedAdminExamsIndexRoute
  AuthenticatedAdminExamsIdEditRoute: typeof AuthenticatedAdminExamsIdEditRoute
}

const AuthenticatedAdminExamsRouteChildren: AuthenticatedAdminExamsRouteChildren =
  {
    AuthenticatedAdminExamsIndexRoute: AuthenticatedAdminExamsIndexRoute,
    AuthenticatedAdminExamsIdEditRoute: AuthenticatedAdminExamsIdEditRoute,
  }

const AuthenticatedAdminExamsRouteWithChildren =
  AuthenticatedAdminExamsRoute._addFileChildren(
    AuthenticatedAdminExamsRouteChildren,
  )

interface AuthenticatedAdminQuizzesRouteChildren {
  AuthenticatedAdminQuizzesNewRoute: typeof AuthenticatedAdminQuizzesNewRoute
  AuthenticatedAdminQuizzesIndexRoute: typeof AuthenticatedAdminQuizzesIndexRoute
  AuthenticatedAdminQuizzesIdEditRoute: typeof AuthenticatedAdminQuizzesIdEditRoute
  AuthenticatedAdminQuizzesIdResultsRoute: typeof AuthenticatedAdminQuizzesIdResultsRoute
}

const AuthenticatedAdminQuizzesRouteChildren: AuthenticatedAdminQuizzesRouteChildren =
  {
    AuthenticatedAdminQuizzesNewRoute: AuthenticatedAdminQuizzesNewRoute,
    AuthenticatedAdminQuizzesIndexRoute: AuthenticatedAdminQuizzesIndexRoute,
    AuthenticatedAdminQuizzesIdEditRoute: AuthenticatedAdminQuizzesIdEditRoute,
    AuthenticatedAdminQuizzesIdResultsRoute:
      AuthenticatedAdminQuizzesIdResultsRoute,
  }

const AuthenticatedAdminQuizzesRouteWithChildren =
  AuthenticatedAdminQuizzesRoute._addFileChildren(
    AuthenticatedAdminQuizzesRouteChildren,
  )

interface AuthenticatedAdminRouteRouteChildren {
  AuthenticatedAdminAdsRoute: typeof AuthenticatedAdminAdsRoute
  AuthenticatedAdminCreatorsRoute: typeof AuthenticatedAdminCreatorsRoute
  AuthenticatedAdminExamsRoute: typeof AuthenticatedAdminExamsRouteWithChildren
  AuthenticatedAdminGuidesRoute: typeof AuthenticatedAdminGuidesRoute
  AuthenticatedAdminNotificationsRoute: typeof AuthenticatedAdminNotificationsRoute
  AuthenticatedAdminPaymentsRoute: typeof AuthenticatedAdminPaymentsRoute
  AuthenticatedAdminProofsRoute: typeof AuthenticatedAdminProofsRoute
  AuthenticatedAdminQuizzesRoute: typeof AuthenticatedAdminQuizzesRouteWithChildren
  AuthenticatedAdminSettingsRoute: typeof AuthenticatedAdminSettingsRoute
  AuthenticatedAdminStudentsRoute: typeof AuthenticatedAdminStudentsRoute
  AuthenticatedAdminUsersRoute: typeof AuthenticatedAdminUsersRoute
  AuthenticatedAdminIndexRoute: typeof AuthenticatedAdminIndexRoute
}

const AuthenticatedAdminRouteRouteChildren: AuthenticatedAdminRouteRouteChildren =
  {
    AuthenticatedAdminAdsRoute: AuthenticatedAdminAdsRoute,
    AuthenticatedAdminCreatorsRoute: AuthenticatedAdminCreatorsRoute,
    AuthenticatedAdminExamsRoute: AuthenticatedAdminExamsRouteWithChildren,
    AuthenticatedAdminGuidesRoute: AuthenticatedAdminGuidesRoute,
    AuthenticatedAdminNotificationsRoute: AuthenticatedAdminNotificationsRoute,
    AuthenticatedAdminPaymentsRoute: AuthenticatedAdminPaymentsRoute,
    AuthenticatedAdminProofsRoute: AuthenticatedAdminProofsRoute,
    AuthenticatedAdminQuizzesRoute: AuthenticatedAdminQuizzesRouteWithChildren,
    AuthenticatedAdminSettingsRoute: AuthenticatedAdminSettingsRoute,
    AuthenticatedAdminStudentsRoute: AuthenticatedAdminStudentsRoute,
    AuthenticatedAdminUsersRoute: AuthenticatedAdminUsersRoute,
    AuthenticatedAdminIndexRoute: AuthenticatedAdminIndexRoute,
  }

const AuthenticatedAdminRouteRouteWithChildren =
  AuthenticatedAdminRouteRoute._addFileChildren(
    AuthenticatedAdminRouteRouteChildren,
  )

interface AuthenticatedQuizQuizIdRouteChildren {
  AuthenticatedQuizQuizIdTakeRoute: typeof AuthenticatedQuizQuizIdTakeRoute
  AuthenticatedQuizQuizIdIndexRoute: typeof AuthenticatedQuizQuizIdIndexRoute
  AuthenticatedQuizQuizIdResultAttemptIdRoute: typeof AuthenticatedQuizQuizIdResultAttemptIdRoute
}

const AuthenticatedQuizQuizIdRouteChildren: AuthenticatedQuizQuizIdRouteChildren =
  {
    AuthenticatedQuizQuizIdTakeRoute: AuthenticatedQuizQuizIdTakeRoute,
    AuthenticatedQuizQuizIdIndexRoute: AuthenticatedQuizQuizIdIndexRoute,
    AuthenticatedQuizQuizIdResultAttemptIdRoute:
      AuthenticatedQuizQuizIdResultAttemptIdRoute,
  }

const AuthenticatedQuizQuizIdRouteWithChildren =
  AuthenticatedQuizQuizIdRoute._addFileChildren(
    AuthenticatedQuizQuizIdRouteChildren,
  )

interface AuthenticatedRouteRouteChildren {
  AuthenticatedAdminRouteRoute: typeof AuthenticatedAdminRouteRouteWithChildren
  AuthenticatedAdsRoute: typeof AuthenticatedAdsRoute
  AuthenticatedCreateRoute: typeof AuthenticatedCreateRoute
  AuthenticatedExamsRoute: typeof AuthenticatedExamsRoute
  AuthenticatedExploreRoute: typeof AuthenticatedExploreRoute
  AuthenticatedNotificationsRoute: typeof AuthenticatedNotificationsRoute
  AuthenticatedResultsRoute: typeof AuthenticatedResultsRoute
  AuthenticatedSupportRoute: typeof AuthenticatedSupportRoute
  AuthenticatedWalletRoute: typeof AuthenticatedWalletRoute
  AuthenticatedIndexRoute: typeof AuthenticatedIndexRoute
  AuthenticatedExamExamIdRoute: typeof AuthenticatedExamExamIdRoute
  AuthenticatedMessagesUserIdRoute: typeof AuthenticatedMessagesUserIdRoute
  AuthenticatedProfileUserIdRoute: typeof AuthenticatedProfileUserIdRoute
  AuthenticatedQuizQuizIdRoute: typeof AuthenticatedQuizQuizIdRouteWithChildren
  AuthenticatedMessagesIndexRoute: typeof AuthenticatedMessagesIndexRoute
  AuthenticatedProfileIndexRoute: typeof AuthenticatedProfileIndexRoute
  AuthenticatedMessagesGroupGroupIdRoute: typeof AuthenticatedMessagesGroupGroupIdRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedAdminRouteRoute: AuthenticatedAdminRouteRouteWithChildren,
  AuthenticatedAdsRoute: AuthenticatedAdsRoute,
  AuthenticatedCreateRoute: AuthenticatedCreateRoute,
  AuthenticatedExamsRoute: AuthenticatedExamsRoute,
  AuthenticatedExploreRoute: AuthenticatedExploreRoute,
  AuthenticatedNotificationsRoute: AuthenticatedNotificationsRoute,
  AuthenticatedResultsRoute: AuthenticatedResultsRoute,
  AuthenticatedSupportRoute: AuthenticatedSupportRoute,
  AuthenticatedWalletRoute: AuthenticatedWalletRoute,
  AuthenticatedIndexRoute: AuthenticatedIndexRoute,
  AuthenticatedExamExamIdRoute: AuthenticatedExamExamIdRoute,
  AuthenticatedMessagesUserIdRoute: AuthenticatedMessagesUserIdRoute,
  AuthenticatedProfileUserIdRoute: AuthenticatedProfileUserIdRoute,
  AuthenticatedQuizQuizIdRoute: AuthenticatedQuizQuizIdRouteWithChildren,
  AuthenticatedMessagesIndexRoute: AuthenticatedMessagesIndexRoute,
  AuthenticatedProfileIndexRoute: AuthenticatedProfileIndexRoute,
  AuthenticatedMessagesGroupGroupIdRoute:
    AuthenticatedMessagesGroupGroupIdRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AuthRoute: AuthRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  ShareQuizQuizIdRoute: ShareQuizQuizIdRoute,
  ApiPublicHooksMonnifyRoute: ApiPublicHooksMonnifyRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
