CREATE TABLE public.ai_threads (
  id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  user_id uuid NOT NULL REFERENCES auth.users(id) ON DELETE CASCADE,
  title text NOT NULL DEFAULT 'New conversation',
  mode text NOT NULL DEFAULT 'guide' CHECK (mode IN ('guide', 'creator')),
  created_at timestamptz NOT NULL DEFAULT now(),
  updated_at timestamptz NOT NULL DEFAULT now()
);
GRANT SELECT, INSERT, UPDATE, DELETE ON public.ai_threads TO authenticated;
GRANT ALL ON public.ai_threads TO service_role;
ALTER TABLE public.ai_threads ENABLE ROW LEVEL SECURITY;
CREATE POLICY "Users can view own AI threads" ON public.ai_threads FOR SELECT TO authenticated USING (auth.uid() = user_id);
CREATE POLICY "Users can create own AI threads" ON public.ai_threads FOR INSERT TO authenticated WITH CHECK (auth.uid() = user_id);
CREATE POLICY "Users can update own AI threads" ON public.ai_threads FOR UPDATE TO authenticated USING (auth.uid() = user_id) WITH CHECK (auth.uid() = user_id);
CREATE POLICY "Users can delete own AI threads" ON public.ai_threads FOR DELETE TO authenticated USING (auth.uid() = user_id);
CREATE INDEX ai_threads_user_updated_idx ON public.ai_threads(user_id, updated_at DESC);
CREATE TRIGGER ai_threads_updated BEFORE UPDATE ON public.ai_threads FOR EACH ROW EXECUTE FUNCTION public.set_updated_at();

CREATE TABLE public.ai_messages (
  id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  thread_id uuid NOT NULL REFERENCES public.ai_threads(id) ON DELETE CASCADE,
  user_id uuid NOT NULL REFERENCES auth.users(id) ON DELETE CASCADE,
  ai_message_id text,
  role text NOT NULL CHECK (role IN ('user', 'assistant', 'system')),
  message jsonb NOT NULL,
  position bigint GENERATED BY DEFAULT AS IDENTITY,
  created_at timestamptz NOT NULL DEFAULT now(),
  UNIQUE (thread_id, ai_message_id)
);
GRANT SELECT, INSERT, UPDATE, DELETE ON public.ai_messages TO authenticated;
GRANT ALL ON public.ai_messages TO service_role;
ALTER TABLE public.ai_messages ENABLE ROW LEVEL SECURITY;
CREATE POLICY "Users can view own AI messages" ON public.ai_messages FOR SELECT TO authenticated USING (auth.uid() = user_id AND EXISTS (SELECT 1 FROM public.ai_threads t WHERE t.id = thread_id AND t.user_id = auth.uid()));
CREATE POLICY "Users can create own AI messages" ON public.ai_messages FOR INSERT TO authenticated WITH CHECK (auth.uid() = user_id AND EXISTS (SELECT 1 FROM public.ai_threads t WHERE t.id = thread_id AND t.user_id = auth.uid()));
CREATE POLICY "Users can update own AI messages" ON public.ai_messages FOR UPDATE TO authenticated USING (auth.uid() = user_id AND EXISTS (SELECT 1 FROM public.ai_threads t WHERE t.id = thread_id AND t.user_id = auth.uid())) WITH CHECK (auth.uid() = user_id AND EXISTS (SELECT 1 FROM public.ai_threads t WHERE t.id = thread_id AND t.user_id = auth.uid()));
CREATE POLICY "Users can delete own AI messages" ON public.ai_messages FOR DELETE TO authenticated USING (auth.uid() = user_id AND EXISTS (SELECT 1 FROM public.ai_threads t WHERE t.id = thread_id AND t.user_id = auth.uid()));
CREATE INDEX ai_messages_thread_position_idx ON public.ai_messages(thread_id, position);

CREATE TABLE public.push_delivery_log (
  id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  user_id uuid REFERENCES auth.users(id) ON DELETE SET NULL,
  endpoint_host text,
  status integer,
  ok boolean NOT NULL DEFAULT false,
  expired boolean NOT NULL DEFAULT false,
  error text,
  public_key_fingerprint text,
  payload jsonb NOT NULL DEFAULT '{}'::jsonb,
  created_at timestamptz NOT NULL DEFAULT now()
);
GRANT SELECT ON public.push_delivery_log TO authenticated;
GRANT ALL ON public.push_delivery_log TO service_role;
ALTER TABLE public.push_delivery_log ENABLE ROW LEVEL SECURITY;
CREATE POLICY "Users can view own push deliveries" ON public.push_delivery_log FOR SELECT TO authenticated USING (auth.uid() = user_id);
CREATE POLICY "Admins can view all push deliveries" ON public.push_delivery_log FOR SELECT TO authenticated USING (public.is_super_admin(auth.uid()));
CREATE INDEX push_delivery_user_created_idx ON public.push_delivery_log(user_id, created_at DESC);
CREATE INDEX push_delivery_created_idx ON public.push_delivery_log(created_at DESC);